In [1]:
import numpy as np

# Advanced Indexing in Numpy

Advanced Indexing lets you select specific elements, rows, columns, or subarrays using lists, tuples, or boolean arrays, rather than only slices or single integer positions.

### Basic Indexing

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # 3x3 array

In [12]:
x = a[0] # gets the first row
print("a[0] return: \n", x)

x = a[0][1] # gets the element at (0, 1)
print("a[0][1] return: \n", x)

x = a[0:2] # gets rows 0, 1
print("a[0:2] return: \n", x)

x = a[0:2, :] # same as above
print("a[0:2, :] return: \n", x)

x = a[:, 1] # get all rows, 2nd column
print("a[:, 1] return: \n", x)

a[0] return: 
 [1 2 3]
a[0][1] return: 
 2
a[0:2] return: 
 [[1 2 3]
 [4 5 6]]
a[0:2, :] return: 
 [[1 2 3]
 [4 5 6]]
a[:, 1] return: 
 [2 5 8]


### Advanced Indexing with Lists

Use lists or arrays of indices to select arbitrary rows or columns.

In [18]:
# Example: select rows 0 and 2:

a[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [17]:
# Example: select all rows, columns 0 and 2:

a[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [19]:
# Example: select elements at positions (0,0) and (2,2):

a[[0, 2], [0, 2]]  # picks (0,0) and (2,2)

array([1, 9])

### Adding New Axes

Use np.newaxis to add a dimension, often for compatibility in ML models

Where you add the new axis matters

In [20]:
col = a[:, 1]           # shape (3,)
col_new_axis = a[:, 1, np.newaxis]  # shape (3, 1)

col_new_axis

array([[2],
       [5],
       [8]])

### Using Boolean Arrays or Masks to filter data

In [22]:
a[[True, False, True]]  # selects rows 0 and 2

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
a[:, [True, False, True]] # select all rows but only columns 0 and 2 equivalent to a[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [23]:
mask = (a % 2 == 0)  # mask for even numbers
a[mask]  # returns array of even numbers

array([2, 4, 6, 8])

### Copy vs View
- Slicing returns a view (modifications affect original array).
- Advanced indexing (lists, boolean masks) returns a copy (modifications do NOT affect original array).

In [30]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# get a slice and modify it
y = x[0:2]
y[0, 0] = 100

print(x) # x is also modified! Because slicing returns a view, not a copy.

[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


### Slicing a List returns a copy though!

In [37]:
# original list
l = [1, 2, 3]

# sliced list
r = l[:1]
r[0] = 100

print(r, l) # slicing a list returns a copy 


[100] [1, 2, 3]


In [40]:
x = np.arange(9).reshape((3,3))


y = x[:, 2] # this is still a view of x. Since we are still slicing the array

y[0] = 100

print(x, y)

[[  0   1 100]
 [  3   4   5]
 [  6   7   8]] [100   5   8]


### Advanced Indexing (Masks, list indexing, boolean indexing) return a copy

#### Masks

In [42]:
x = np.arange(9).reshape((3,3))

mask = (x > 4)

y = x[mask]  # advanced indexing returns a copy
print(y)
print(x)

[5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Boolean Indexing

In [43]:
x = np.arange(9).reshape((3,3))

y = x[[True, False, True], :]  # advanced indexing returns a copy
y[0, 0] = 100


print(y)
print(x)

[[100   1   2]
 [  6   7   8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


##### List indexing

In [45]:
x = np.arange(9).reshape((3,3))

y = x[[0, 1], [2, 0]]  # advanced indexing returns a copy
y[0] = 100

print(y)
print(x)

[100   3]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### The base attribute of a Numpy array tells you if its a copy or a view

In [46]:
x = np.arange(9).reshape((3,3))

y = x[:, 2]
print(y.base)  # None, since y is a copy


mask = (x > 4)
z = x[mask]
print(z.base)  # None, since z is a copy

[0 1 2 3 4 5 6 7 8]
None
