In [1]:
import numpy as np

# Advanced Indexing in Numpy

Advanced Indexing lets you select specific elements, rows, columns, or subarrays using lists, tuples, or boolean arrays, rather than only slices or single integer positions.

### Basic Indexing

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # 3x3 array

In [12]:
x = a[0] # gets the first row
print("a[0] return: \n", x)

x = a[0][1] # gets the element at (0, 1)
print("a[0][1] return: \n", x)

x = a[0:2] # gets rows 0, 1
print("a[0:2] return: \n", x)

x = a[0:2, :] # same as above
print("a[0:2, :] return: \n", x)

x = a[:, 1] # get all rows, 2nd column
print("a[:, 1] return: \n", x)

a[0] return: 
 [1 2 3]
a[0][1] return: 
 2
a[0:2] return: 
 [[1 2 3]
 [4 5 6]]
a[0:2, :] return: 
 [[1 2 3]
 [4 5 6]]
a[:, 1] return: 
 [2 5 8]


### Advanced Indexing with Lists

Use lists or arrays of indices to select arbitrary rows or columns.

In [18]:
# Example: select rows 0 and 2:

a[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [17]:
# Example: select all rows, columns 0 and 2:

a[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [19]:
# Example: select elements at positions (0,0) and (2,2):

a[[0, 2], [0, 2]]  # picks (0,0) and (2,2)

array([1, 9])

### Adding New Axes

Use np.newaxis to add a dimension, often for compatibility in ML models

Where you add the new axis matters

In [20]:
col = a[:, 1]           # shape (3,)
col_new_axis = a[:, 1, np.newaxis]  # shape (3, 1)

col_new_axis

array([[2],
       [5],
       [8]])

### Using Boolean Arrays or Masks to filter data

In [22]:
a[[True, False, True]]  # selects rows 0 and 2

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
a[:, [True, False, True]] # select all rows but only columns 0 and 2 equivalent to a[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [23]:
mask = (a % 2 == 0)  # mask for even numbers
a[mask]  # returns array of even numbers

array([2, 4, 6, 8])